import type { GlossaryEntry } from "../types";

export const glossary: GlossaryEntry[] = [
  { id: "token", term: "Token", definition: "A chunk of text the model reads or writes. Prices are usually quoted per million tokens. There is no fixed number of words per token.", lessonId: "day1-context" },
  { id: "context-window", term: "Context window", definition: "The maximum amount of input plus generated output a model call can hold. A larger window is not automatically a better answer.", lessonId: "day1-context" },
  { id: "mtok", term: "MTok", definition: "One million tokens. Anthropic list prices are quoted per million tokens.", lessonId: "day3-unit-cost" },
  { id: "system-prompt", term: "System prompt", definition: "Instructions sent with a request that describe how the assistant should behave. It is still only text. It does not grant permissions.", lessonId: "day2-anatomy" },
  { id: "stop-reason", term: "Stop reason", definition: "The API field that says why a response ended, such as end of turn, a tool request, hitting the output cap, or a refusal.", lessonId: "day2-anatomy" },
  { id: "tool-use", term: "Tool use", definition: "The model asks for a tool by name and arguments. The application decides whether to run it. The request itself does not execute the business action.", lessonId: "day2-tools" },
  { id: "json-schema", term: "JSON schema", definition: "A description of the shape of a JSON document: required fields and types. A valid shape can still contain a false fact.", lessonId: "day2-validation" },
  { id: "idempotency", term: "Idempotency", definition: "Repeating the same request does not apply the same side effect twice. A key lets a retry find the original result.", lessonId: "day2-validation" },
  { id: "rate-limit", term: "Rate limit", definition: "A cap on how many requests or tokens you can send in a period. A 429 response means back off. It does not mean the business record is missing.", lessonId: "day2-validation" },
  { id: "prompt-caching", term: "Prompt caching", definition: "Reusing a previously processed prompt prefix so later requests pay a lower cache-read price instead of the full input price.", lessonId: "day3-caching" },
  { id: "cache-write", term: "Cache write", definition: "The first time a prefix is stored. It costs more than ordinary input for a limited lifetime, commonly 5 minutes or 1 hour.", lessonId: "day3-caching" },
  { id: "cache-read", term: "Cache read", definition: "A later request that reuses a stored prefix. It is cheaper than ordinary input only when the prefix still matches and has not expired.", lessonId: "day3-caching" },
  { id: "batch-api", term: "Batch API", definition: "An asynchronous way to send many requests at a lower list price when the user can wait.", lessonId: "day3-batch" },
  { id: "sso", term: "SSO", definition: "Single sign-on. People sign in through the company’s identity provider instead of a separate password.", lessonId: "day4-controls" },
  { id: "scim", term: "SCIM", definition: "A standard for provisioning users and groups from an identity provider. It keeps joiners and leavers in sync.", lessonId: "day4-controls" },
  { id: "audit-log", term: "Audit log", definition: "A record of administrative and product actions used for review. Enterprise export rules are documented separately from API logs.", lessonId: "day4-controls" },
  { id: "rag", term: "RAG", definition: "Retrieval-augmented generation. The application searches source material and puts selected passages into the prompt. It does not guarantee the answer is true.", lessonId: "day5-why" },
  { id: "chunk", term: "Chunk", definition: "A piece of a document small enough to retrieve. Overlap keeps a sentence from being cut away from the sentence it depends on.", lessonId: "day5-pipeline" },
  { id: "embedding", term: "Embedding", definition: "A numeric representation used for similarity search. This lab’s ranker is lexical term overlap and is not an embedding model.", lessonId: "day5-pipeline" },
  { id: "top-k", term: "Top-k", definition: "How many retrieved chunks are passed to the model. A larger k includes more text and also more chances to include the wrong text.", lessonId: "day5-pipeline" },
  { id: "groundedness", term: "Groundedness", definition: "Whether an answer stays within the supplied sources. A fluent answer can still be ungrounded.", lessonId: "day6-evals" },
  { id: "precision", term: "Precision", definition: "Of the items the system flagged, how many were truly in the class you care about.", lessonId: "day6-evals" },
  { id: "recall", term: "Recall", definition: "Of the items that truly belong in the class, how many the system caught.", lessonId: "day6-gates" },
  { id: "held-out", term: "Held-out set", definition: "Examples you do not use while tuning the prompt, so the score is less flattered by memorizing the practice set.", lessonId: "day6-evals" },
  { id: "mcp", term: "MCP", definition: "Model Context Protocol. A way for an assistant to connect to external tools. Connecting a tool is not the same as authorizing every action it can take.", lessonId: "day6-code" },
  { id: "claude-code", term: "Claude Code", definition: "Anthropic’s coding assistant. Its command approvals, Enterprise seat controls, and Console API keys are different control planes.", lessonId: "day6-code" },
  { id: "consumption", term: "Consumption", definition: "API usage billed from tokens and features, as distinct from a per-seat subscription. Useful consumption is completed work, not raw tokens.", lessonId: "day7-health" },
];
